---
- name: Configure jenkins ci
  hosts: localhost
  vars:
    jenkins_home: /efs/jenkins
    jenkins_plugins: [ job-dsl git ws-cleanup envinject shiningpanda ]
    jenkins_admin_username: admin
    jenkins_admin_password: '{{ admin_password }}'
  roles:
    - aws-cfn-bootstrap
    - awscli
    - geerlingguy.jenkins

